### ISSUE TITLE
Update internal links

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cawesome-wasm#1]
For official smart contracts, we only have two. You can add the rest of https://github.com/CosmWasm/cosmwasm-examples there as simple examples

Also, please add a section for https://github.com/CosmWasm/cosmwasm-plus broken down by spec (CW20, CW1)....

Also cosmwasm-opt has now been deprescated and replaced with https://github.com/CosmWasm/rust-optimizer

Oh, and cw-storage is now inside the `cosmwasm` repo, as `packages/storage`, which serves the same purpose, but is inside the main repo.

**Comment by orkunkl** [comment]
I'll detail cosmwasm-plus section. The main difference between https://github.com/CosmWasm/cosmwasm-examples and https://github.com/CosmWasm/cosmwasm-plus/tree/master/contracts is latter is product grade but cosmwasm-examples repo contains cw-escrow and cw-erc20 as well. Should I move these 2 contracts from examples repo to plus repo? @ethanfrey

**Comment by ethanfrey** [comment]
The contracts with cosmwasm-examples are more limited. `cw-escrow` only works with native tokens, which `cw20-escrow` works with native or whitelisted cw20 tokens.

`cw20` is our own defined spec, inspired by erc20 and erc777. erc20 is a direct port of a basic openzepplin contract.

The `examples` are simpler and maybe nice for people to get started. The `plus` side are designed with a cosmwasm-specific spec and focus on composability.

No need to move anything from examples to plus. `cw1-multisig` (which I should rename) is a somewhat improved version of `mask` from examples.  Maybe we deprecate examples sometime?

**Comment by orkunkl** [comment]
Yes, we can deprecate them as we have more detailed contracts. The main point should be keeping trivial and product-grade contracts organized and separate.
